import reflex as rx
from client.state.findpwd_st import FindpwdState
from .components.alert_dialog import alert_dialog
from .components.theme_wrap import theme_wrap_out


def findpwd():
    return theme_wrap_out(
        rx.center(
            rx.card(
                rx.flex(
                    rx.heading(
                        "找回密码",
                        align="center"
                    ),
                    rx.form(
                        rx.flex(
                            rx.flex(
                                rx.text(
                                    "邮箱",
                                    size="3",
                                    weight="medium",
                                    text_align="left",
                                    width="100%",
                                ),
                                rx.input(
                                    rx.input.slot(rx.icon("mail")),
                                    placeholder="输入邮箱",
                                    name="email",
                                    on_change=lambda x: FindpwdState.set_email(x),
                                    size="3",
                                ),
                                direction='column',
                                spacing='1'
                            ),
                            rx.flex(
                                rx.text(
                                    "验证码",
                                    size="3",
                                    weight="medium",
                                    text_align="left",
                                    width="100%",
                                ),
                                rx.flex(
                                    rx.input(
                                        rx.input.slot(rx.icon("shield-check")),
                                        placeholder="验证码",
                                        name="captcha",
                                        size="3",
                                        width="60%",
                                    ),
                                    rx.button(
                                        rx.cond(
                                            FindpwdState.countdown > 0,
                                            f"重新发送 ({FindpwdState.countdown}s)",
                                            "发送验证码"
                                        ),
                                        type="button",
                                        on_click=FindpwdState.send_email,
                                        variant='surface',
                                        size="3",
                                        disabled=FindpwdState.countdown > 0,
                                        width="40%",
                                    ),
                                    direction="row",
                                    align="center",
                                    justify="center",
                                    spacing="4"
                                ),
                                direction='column',
                                spacing='1'
                            ),
                            rx.flex(
                                rx.text(
                                    "密码",
                                    size="3",
                                    weight="medium",
                                    text_align="left",
                                    width="100%",
                                ),
                                rx.input(
                                    rx.input.slot(rx.icon("key-round")),
                                    type="password",
                                    name="password",
                                    placeholder="输入密码",
                                    size="3",
                                ),
                                direction='column',
                                spacing='1'
                            ),
                            rx.flex(
                                rx.text(
                                    "确认密码",
                                    size="3",
                                    weight="medium",
                                    text_align="left",
                                    width="100%",
                                ),
                                rx.input(
                                    rx.input.slot(rx.icon("key-round")),
                                    type="password",
                                    name="confirm_password",
                                    placeholder="再次确认密码",
                                    size="3",
                                ),
                                direction='column',
                                spacing='1'
                            ),
                            rx.button(
                                "提交",
                                type="submit",
                                variant='surface',
                                size="3",
                                width="100%",
                            ),
                            spacing="4",
                            direction="column"
                        ),
                        padding="32px",
                        width="100%",
                        on_submit=FindpwdState.change_pwd,
                        reset_on_submit=False,
                    ),
                    rx.text(
                        rx.link(
                            "点击此处返回登录页面。", 
                            href="/login"
                        ),
                    ),
                    align="center",
                    justify="center",
                    width="100%",
                    height="100%",
                    direction="column",
                    spacing="4",
                    padding='30px'
                ),
                width="600px",
            ),
            alert_dialog(
                description=FindpwdState.findpwd_dialog_description,
                on_click=FindpwdState.findpwd_dialog_open_change,
                open=FindpwdState.findpwd_dialog_open
            ),
            alert_dialog(
                description=FindpwdState.findpwd_dialog_description,
                on_click=FindpwdState.findpwd_success_redirect,
                open=FindpwdState.findpwdsuccess_dialog_open
            ),
            width="100%",
            height="100vh",
        )
    )
